name: subpred4
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - black
  - ipykernel
  - conda-forge::yellowbrick
  - conda-forge::imbalanced-learn
  - joblib
  - matplotlib
  - flake8
  - seaborn
  - fastcluster
  - bioconda::cd-hit
  - bioconda::blast
  - openpyxl
  - nbconvert
  - jupyter
  - conda-forge::owlready2
  - venn
  - mmseqs2
  - ca-certificates
  - certifi
  - openssl
  - gensim
  - h5py
  - tabulate
  - obonet
  - pygraphviz
  - pigz
  - rdkit
  - rpy2
  - bioconda::bioconductor-gosemsim
  - bioconda::bioconductor-org.sc.sgd.db
